pipeline {
    agent any
    stages {
        stage('Build Backend') {
            steps {
                dir('backend') {
                    bat 'mvn clean package -Dskip.surefire.tests'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                dir('backend') {
                    bat 'mvn test'
                }
            }
        }
        stage('Deploy Backend Dev') {
            steps {
                dir('backend/target') {
                    bat 'java -Delastic.username=elastic -Delastic.password=elastic -jar record-0.0.1-SNAPSHOT.jar'
                }
            }
        }
        stage('Integration Tests') {            
            steps {
                sleep(time: 10, unit: "SECONDS")
                dir('backend') {
                    bat 'mvn test -Dtest=RecordControllerTest.java'
                }
            }
        }
        stage('Verify Deploy') {            
            steps {
                sleep(time: 10, unit: "SECONDS")
                dir('backend') {
                    bat 'mvn verify -Dskip.surefire.tests'
                }
            }
        }
    }
    post {
        success {
            emailext attachLog: true, body: 'Veja o log abaixo', subject: 'Build/Deploy realizados com sucesso.', to: 'murilodev.lima@outlook.com'
        }
        unsuccessful {
            emailext attachLog: true, body: 'Veja o log abaixo', subject: 'Build falhou', to: 'murilodev.lima@outlook.com'
        }
    }
}